FROM node:18-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code source
COPY . .

# Exposer le port du frontend
EXPOSE 3000

# Démarrer le serveur de développement Vite
CMD ["npm", "run", "dev", "--", "--host"]
