FROM node:18-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code source
COPY . .

# Build de production
RUN npm run build

# Installer le serveur statique pour la production
RUN npm install -g serve

# Exposer le port du frontend
EXPOSE 80

# Servir le build de production
CMD ["serve", "-s", "dist", "-l", "80"]
